from . import hr_employee
from . import hr_employee_academic
from . import hr_employee_history
from . import hr_employee_institution
from . import hr_employee_reference
from . import hr_employee_birth_place
from . import hr_employee_tribe
from . import hr_employee_religion
from . import hr_employee_children
from . import hr_employee_relation
from . import hr_employee_children_occupation
from . import hr_employee_work_place
from . import hr_district
from . import hr_province
from . import hr_employee_referees
from . import email_check
from . import hr_occupation
from . import hr_qualification

